name: CI

on:
  pull_request:
    paths-ignore: ['docs/**', '**/README.rst']
  push:
    branches: [main]
    paths-ignore: ['docs/**', '**/README.rst']
  workflow_dispatch:
  
jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: ["net-configurator"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: ${{ matrix.project }}/pyproject.toml

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        working-directory: ${{ matrix.project }}
        run: poetry install --with dev

      - name: Run Ruff check
        working-directory: ${{ matrix.project }}
        run: poetry run ruff check

      - name: Run Ruff format
        working-directory: ${{ matrix.project }}
        run: poetry run ruff format --diff

      - name: Run Mypy
        working-directory: ${{ matrix.project }}
        run: poetry run mypy

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: ["net-configurator"]
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version-file: ${{ matrix.project }}/pyproject.toml

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install dependencies
      working-directory: ${{ matrix.project }}
      run: poetry install --with dev

    - name: Run Pytest
      working-directory: ${{ matrix.project }}
      run: poetry run pytest
